<?php
/*
 * This file is part of the Wam Web Asset Manager Package
 * This file was auto-generated by Wam
 *
 * (c) Pete Robinson <work@pete-robinson.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE file
 */
namespace Acme\TestBundle\WamEntity;
use Wam\AssetBundle\Entity\Base\AbstractEntity;

final class Product extends AbstractEntity
{
	/**
	 * dirs
	 * @var array
	 */
	protected $dirs = array(
		'products/{id}',
		'products/{id}/images',
		array(
			'path' => 'products/{id}/images/100',
			'method' => 'height'
		),
		'products/{id}/images/200',
		'products/{id}/images/800',
		'products/{id}/documents'
	);

	
}