<?php
/*
 * This file was auto-generated by Wam
 *
 * (c) Pete Robinson <work@pete-robinson.co.uk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Wam\AssetBundle\Entity\Base\AbstractEntity;
use Wam\AssetBundle\Entity\Base\AssetDefinition;

{{permission}}class FileWriterTest{{extends}}{{implements}}
{
	
	/**
	 * dirs
	 * @var array
	 */
	protected $dirs = array(
		'1',
		'2',
		'3'
	);

	/**
	 * static
	 * @var string
	 */
	protected $static = 'test';

}